name: CI

on: [push, pull_request]

env:
    CARGO_TERM_COLOR: always

jobs:
    build_linux:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
    build_windows:
      runs-on: windows-latest
      steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose      
    build_macos:
      runs-on: macos-latest
      steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
